<a href="https://colab.research.google.com/github/cayo1cezar/matema-tica/blob/main/algebralinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
matriz = np.array([[1,0,0,1],
                   [2,2,2,5],
                  [-3,2,0,0],
                   [1,0,-1,4]])

matriz_2 = np.array([[1,0,3,1],
                     [2,2,2,5],
                     [-1,3,0,0],
                     [9,0,-1,4]])

In [ ]:
matriz

array([[ 1,  0,  0,  1],
       [ 2,  2,  2,  5],
       [-3,  2,  0,  0],
       [ 1,  0, -1,  4]])

In [ ]:
print(matriz)

[[ 1  0  0  1]
 [ 2  2  2  5]
 [-3  2  0  0]
 [ 1  0 -1  4]]


In [ ]:
soma = matriz + matriz_2
print(soma)

[[ 2  0  3  2]
 [ 4  4  4 10]
 [-4  5  0  0]
 [10  0 -2  8]]


In [ ]:
sub = matriz - matriz_2
print(sub)

[[ 0  0 -3  0]
 [ 0  0  0  0]
 [-2 -1  0  0]
 [-8  0  0  0]]


In [ ]:
mult_escalar = matriz *3
print(mult_escalar)

[[ 3  0  0  3]
 [ 6  6  6 15]
 [-9  6  0  0]
 [ 3  0 -3 12]]


In [ ]:
div = matriz/2
print(div)

[[ 0.5  0.   0.   0.5]
 [ 1.   1.   1.   2.5]
 [-1.5  1.   0.   0. ]
 [ 0.5  0.  -0.5  2. ]]


In [ ]:
#Múltiplicação de matrizes 

m = np.dot(matriz, matriz_2 )

print(m)

[[10  0  2  5]
 [49 10  5 32]
 [ 1  4 -5  7]
 [38 -3 -1 17]]


In [ ]:

a = np.array([[0,1], [3,0]])
print(a)

[[0 1]
 [3 0]]


In [ ]:
# Matriz Transposta: Matriz que as linhas viram colunas, e as colunas viram linhas.
# Operador T
t = a.transpose()

r = a.T

print(r)
print('\n')
print(t)

[[0 3]
 [1 0]]


[[0 3]
 [1 0]]


In [ ]:
# Matriz identidade ---> Matrizes Quadradas ( o n de linhas = n de colunas)
# A diagonal principal é 1 para todos os elementos, e o restante é igual a 0.

id = np.eye(3)

print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Matriz Inversa 

$$ A . A^{-1} = I $$

In [ ]:
b = np.array([[0,1], [3,0]])
#i = np.eye(2)

# Calculando a inversa
b_inv = np.linalg.inv(b)

In [ ]:
print(b)
print()
print(b_inv)

[[0 1]
 [3 0]]

[[0.         0.33333333]
 [1.         0.        ]]


In [ ]:
 a = np.array([
     [1,5,3],
     [3,2,1],
     [1,1,1]
 ])

 y = np.array([
     [1],
     [0],
     [1]

 ])
 print(a)
 print()
 print(y)

[[1 5 3]
 [3 2 1]
 [1 1 1]]

[[1]
 [0]
 [1]]


In [ ]:
# resolvendo uma equação matricial de uma forma alternativa

x = np.linalg.solve(a,y)

print(x)

[[ 0.]
 [-1.]
 [ 2.]]


In [ ]:
#Determinantes

m = np.array([
    [1,0,1],
    [2,2,2],
    [-1,4,-2]
])
print(m)

[[ 1  0  1]
 [ 2  2  2]
 [-1  4 -2]]


In [ ]:
det = np.linalg.det(m)
print(det)

-1.9999999999999993


In [ ]:
print(round(det))

-2


In [ ]:
matriz = np.array([
    [2,1],
    [-1,0]
])

autovalores, autovetores = np.linalg.eig(matriz)
print(autovalores)
print()
print(autovetores)

[1. 1.]

[[ 0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [ ]:
matriz_Diagonal = np.diag(autovalores)
print(matriz_Diagonal) 

[[1. 0.]
 [0. 1.]]
